name = "FixedWidthTables"
uuid = "ef6c9296-b25d-482c-a0a7-898918678e13"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.8"

[deps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
StructArrays = "0.6.8"
julia = "1.5"
