name = "FixedWidthTables"
uuid = "ef6c9296-b25d-482c-a0a7-898918678e13"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.2.0"

[deps]
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[weakdeps]
DictArrays = "e9958f2c-b184-4647-9c5a-224a61f6a14b"

[extensions]
DictArraysExt = "DictArrays"

[compat]
DataPipes = "0.3"
DictArrays = "0.1.1"
StructArrays = "0.6.8"
julia = "1.5"
