name = "FixedWidthTables"
uuid = "ef6c9296-b25d-482c-a0a7-898918678e13"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.4-dev"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[compat]
IterTools = "1.3"
julia = "1.5"
